# Generated by Django 4.2.9 on 2024-01-04 23:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('zad3', '0001_initial'),
    ]

    operations = [
    ]
