# Generated by Django 4.2.9 on 2024-01-04 23:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('zad3', '0002_auto_20240105_0035'),
    ]

    operations = [
        migrations.DeleteModel(
            name='YourTable',
        ),
    ]
