# Generated by Django 4.2.9 on 2024-01-06 15:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('zad3', '0004_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Table1',
        ),
    ]
